### ISSUE TITLE
Gulp issues - custom version

### ISSUE THREAD

**Issue by Marten4n6** [picturepan2/spectre#547]
I'm trying to change color variables as shown in the [documentation](https://picturepan2.github.io/spectre/getting-started/custom.html).

Deprecations:
```bash
$ npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated node-uuid@1.4.0: Use uuid module instead
```

```bash
$ gulp build
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/bot/Downloads/spectre/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/bot/Downloads/spectre/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/bot/Downloads/spectre/gulpfile.js:67:6)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

```bash
$ gulp -version
[12:58:15] CLI version 2.0.0
[12:58:15] Local version 4.0.0
```

**Comment by Marten4n6** [comment]
For anyone having this issue, the solution is to downgrade your gulp version:
```bash
# Show available versions of gulp
$ npm view gulp versions
# Install an older version
$ npm install gulp@3.8.11
# Verify the newly installed version
$ gulp -version 

# "gulp build" should now work, if it doesn't mess with the version number
```

Maybe it's a good idea to specify the required gulp version in the documentation?
Thanks.

**Comment by rgeronimi** [comment]
Or update the package.json to require gulp@3.9.1 rather than its latest version?

**Comment by sukima** [comment]
I'm confused. Why is this closed if it hasn't been fixed? Per the package.json this repo is compatible with `"gulp": "latest"` which *clearly* it is **not**! This issue needs to stay open till either the repo is *indeed* compatible with **latest** or has locked its gulp version to a compatible one.

Also the documentation states running `gulp build` is all you need. This is not true. when installed via `npm install` the `gulp` executable is not in the users' path by default. Either the user needs to execute `npx gulp build` or the `package.json` file needs to define a `"scripts"` section.
