### ISSUE TITLE
ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by Marten4n6** [picturepan2/spectre#573]
When attempting to do ```gulp build``` I always get (after ```npm install```):
```bash
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/bot/Downloads/Testing-css/spectre-0.5.8/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/bot/Downloads/Testing-css/spectre-0.5.8/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/bot/Downloads/Testing-css/spectre-0.5.8/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
```

*Solution*:
```npm install natives@1.1.6```

**Comment by DanielRuf** [comment]
Hi, can you provide a PR?

**Comment by renegat59** [comment]
Hi,
installing `natives@1.1.6` is more of a workaround not a solution. You can work it out by installing node `9.x`. As a temporary solution I added `natives@1.1.6`, but eventually it would make sense to migrate the project to use gulp 4.x.
Pull request:
https://github.com/picturepan2/spectre/pull/575

**Comment by DanielRuf** [comment]
Better use Node.js 8 as 9 is not a LTS release branch.

**Comment by DanielRuf** [comment]
But as this is not a repo under an org account the truck number is 1. So it might take a while. Also it seems there are not many PRs merged.

**Comment by renegat59** [comment]
> Better use Node.js 8 as 9 is not a LTS release branch.

Fair point. And with 8 will also work fine.
I am actually waiting for a few other fixes so I hope there will be some progress with the PR merges soon.
